### ISSUE TITLE
[DIP 1: DIATAXIFY] Docs: Structure

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#108]
This is an issue to track all of the desired changes for updating the docs. The context for the docs changes are going through the current docs and thinking about how we can improve them based on Learning Journeys.

Add issues here:
```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/110
- [ ] https://github.com/AztecProtocol/dev-rel/issues/115
- [ ] https://github.com/AztecProtocol/dev-rel/issues/116
- [ ] Consider adding a "Development" page to Foundational Concepts section that describes the Sandbox/CLI and links to the detailed pages
- [x] remove this page: https://docs.aztec.network/dev_docs/aztecjs/main
- [ ] https://github.com/AztecProtocol/dev-rel/issues/111
- [ ] Consider trimming down the About Aztec section
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/3282
- [ ] https://github.com/AztecProtocol/dev-rel/issues/73
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/3715
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/4157
```

Learning journey references:
- [1-pager (WIP)](https://docs.google.com/document/d/1YRw4ysHI1ibbe1nBBx4KN7XX0RpI5FtleRAPR9lYYFQ/edit#heading=h.34ftsyuofdg7)
- [mindmap](https://www.mindmeister.com/app/map/3110603953?t=oWDwlsESBd)

**Comment by critesjosh** [comment]
A small piece of feedback that I'm not sure how to add to the list. 

The docs talk about proving things. for smart contract devs, proving often means something different in zk land vs smart contract land. proving for Ethereum devs means revealing all of the data, not so for aztec

**Comment by critesjosh** [comment]
Also, at the top of some pages, it says "you will learn X on this page". Consider adding "if you want to learn Y go to these pages", for the case where someone lands on that page that is actually looking for a related topic.

**Comment by catmcgee** [comment]
You can find the new proposed structure [on Notion](https://www.notion.so/catmcgee-noir-playground/New-Structure-428855cfde76401fb5c1cdab3131758b?pvs=4)

**Comment by critesjosh** [comment]
@catmcgee is this work carrying on into this week's iteration?
