### ISSUE TITLE
Noir Docs Learning Journeys

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#119]
```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/127
- [ ] https://github.com/AztecProtocol/dev-rel/issues/126
- [ ] https://github.com/AztecProtocol/dev-rel/issues/125
```

**Comment by signorecello** [comment]
Converting this to an epic of sorts

**Comment by critesjosh** [comment]
Is this issue still in progress, or should we move it back to the backlog for now?
