### ISSUE TITLE
Protocol Webinars

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#135]
- Identify webinars topics and subject matter experts
- Dev rel to collate content, ask clarifying questions from engineers
- Hand off to editors
- Include final versions in content (docs, awesome-aztec, handbook, etc)
- Planning doc here: https://docs.google.com/document/d/11EesaWF3931ibyRw9Wgbc-nHCIB2FMuPTtI_m2hVgZ4/edit

```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/173
- [ ] https://github.com/AztecProtocol/dev-rel/issues/176
- [ ] https://github.com/AztecProtocol/dev-rel/issues/175
- [ ] Protocol Webinars Topic -- Private message delivery / note discovery
- [ ] Protocol Webinars Topic -- Addresses and Keys
- [ ] Protocol Webinars Topic -- Contract Composability
- [ ] Protocol Webinars Topic -- Cross Chain communicaiton
- [ ] Protocol Webinars Topic -- Cryptography
- [ ] Protocol Webinars Topic -- Circuits
- [ ] Protocol Webinars Topic -- Public VM
- [ ] Protocol Webinars Topic -- Logging
- [ ] Protocol Webinars Topic -- Bytecode
- [ ] Protocol Webinars Topic -- Gas/fees
- [ ] Protocol Webinars Topic -- Governance / Updgrades
- [ ] Protocol Webinars Topic -- Block production
- [ ] Protocol Webinars Topic -- P2P networking
```

**Comment by catmcgee** [comment]
is this continuous?

**Comment by critesjosh** [comment]
[Working doc](https://docs.google.com/document/d/11EesaWF3931ibyRw9Wgbc-nHCIB2FMuPTtI_m2hVgZ4/edit)

**Comment by critesjosh** [comment]
Update: Reached out to domain experts to get input on presenters

**Comment by critesjosh** [comment]
closing in favor of https://github.com/AztecProtocol/dev-rel/issues/224
