### ISSUE TITLE
[DIP 3: GITHUB] Docs: Remove need to go to GitHub when building

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#143]
```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/3623
- [ ] https://github.com/AztecProtocol/dev-rel/issues/140
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/3121
```

**Comment by critesjosh** [comment]
@catmcgee I suggested to @jzaki that we de-prioritize https://github.com/AztecProtocol/aztec-packages/issues/3121 to focus more on writing Aztec contracts and e2e tests (rather than focusing on the internals of Aztec.nr). Considering that, should we close this issue and leave 3121 as future work?

**Comment by critesjosh** [comment]
I am going to move this to the backlog since the 1 remaining issue is also in the backlog

**Comment by critesjosh** [comment]
closing bc all referenced issues are also closed.
