### ISSUE TITLE
Boxes EPIC

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#145]
First of all, boxes are broken. Tests pass but running the frontend doesn't and the README is outdated.

But we also don't know _what_ they are. Are they e2e tests? Are they boilerplates? Are they examples? No one knows. Let's find out what they are and see what can we do with them.

```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/134
- [ ] https://github.com/AztecProtocol/dev-rel/issues/146
- [ ] https://github.com/AztecProtocol/dev-rel/issues/147
- [ ] https://github.com/AztecProtocol/dev-rel/issues/149
- [ ] https://github.com/AztecProtocol/dev-rel/issues/150
- [ ] https://github.com/AztecProtocol/dev-rel/issues/177
- [ ] https://github.com/AztecProtocol/dev-rel/issues/179
- [ ] https://github.com/AztecProtocol/dev-rel/issues/184
- [ ] https://github.com/AztecProtocol/dev-rel/issues/192
```

**Comment by critesjosh** [comment]
@signorecello how's the progress on the outstanding issues for this? do you have capacity for these or do you need help?

**Comment by signorecello** [comment]
The boxes themselves are done. Looking at the task list, I think I'm missing the codespaces and I think this could be useful and hopefully not a lot of work. Will add to planning but I think we will agree to proceed to codespaces

**Comment by signorecello** [comment]
Done, one task missing regarding the buttons and CTA. The default github codespaces badges simply say "open in codespaces". Not what we want. Plus we should maybe have some nice branding.

So I sent a design request to Julian, and I'm blocking this until he gets back with it
