### ISSUE TITLE
Update stealthdrop in noir-examples

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#181]
```[tasklist]
### Tasks
- [ ] Updating merkle tree implementation with zk-kit's version (passing in the bb poseidon hash function)
- [ ] Updating the example with a more recent-ish version of Noir
- [ ] Update the circuit to use poseidon2 as hash function instead of pedersen
- [ ] Finish the fronten
- [ ] Update the smart contracts
- [ ] PLUME integration
```

**Comment by critesjosh** [comment]
@signorecello are you able to pick this up or should we move it back to the backlog?

**Comment by signorecello** [comment]
I think this was on @jzaki ? But I see him with recursion, so maybe it was @catmcgee 😄 otherwise I wouldn't move it to the backlog, instead I'd discuss if we can finally hire some contractor to do the frontend for this. I'll add it to planning

**Comment by catmcgee** [comment]
think it was @jzaki because i was originally on recursion til alpha took my time! i can take this if @jzaki wants to continue on recursion

**Comment by jzaki** [comment]
Recursion PR ready for review [207](https://github.com/AztecProtocol/dev-rel/pull/207)
