### ISSUE TITLE
Add tracking to Aztec and Noir Docs

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#211]
```[tasklist]
### Tasks
- [x] SPIKE multiple options such as datadog, gtag, etc
- [x] Check out a GDPR compliant banner we can use
- [x] Implement
- [x] sync with legal
- [x] push to prod
```

**Comment by signorecello** [comment]
Made it 1 week long as @critesjosh already had a look at the GDPR banners and apparently they aren't easy to come by, I may need to ask Julian to design one.

Also need to SPIKE our options on which service to use. If we go self-hosted it can become a bit harder to implement but fear not, I'll do it

**Comment by critesjosh** [comment]
It would be good have a list of requirements we want from the analytics service we use. 

Some things that come to mind

- tracking user flow through the docs. Which pages they visit in which order
- GDPR compliant
- number of page views for each page

Nice to have:

- location 
- time spent on each page

Tagging @rahul-kothari for any additional suggestions

**Comment by signorecello** [comment]
[Notion doc](https://zpedro.notion.site/Analytics-54913bdb6e974a12a18ffdb724301137?pvs=4) where I'm tracking our thoughts and progress

**Comment by critesjosh** [comment]
changes included in #221

**Comment by rahul-kothari** [comment]
I'd like to see:
* Page views
* click paths (sequence of pages visited by user)
* search queries
* scroll depth/speed (Monitor how far users scroll down on each page. This can indicate whether users are engaging with the entire content or if they are finding the information they need quickly.)
