### ISSUE TITLE
Keep minimum set of tutorials for each of Finance, IAM and Gaming and keep up to date

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#212]
### Rationale for pursuing this strategy: 

We want to do this because Finance, IAM, and Gaming are the commercial teams target verticals and we want to help developers  explore the design space and build applications in these verticals. Demonstrating and explaining to developers about how to build at least one example application in each vertical will help them learn how to think about and execute on building on Aztec. 

```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/227
- [ ] https://github.com/AztecProtocol/dev-rel/issues/228
- [ ] https://github.com/AztecProtocol/dev-rel/issues/229
- [ ] https://github.com/AztecProtocol/dev-rel/issues/230
- [ ] https://github.com/AztecProtocol/dev-rel/issues/231
- [ ] https://github.com/AztecProtocol/dev-rel/issues/232
- [ ] https://github.com/AztecProtocol/dev-rel/issues/233
- [ ] https://github.com/AztecProtocol/dev-rel/issues/234
- [ ] https://github.com/AztecProtocol/dev-rel/issues/235
- [ ] https://github.com/AztecProtocol/dev-rel/issues/236
- [ ] https://github.com/AztecProtocol/dev-rel/issues/238
- [ ] https://github.com/AztecProtocol/dev-rel/issues/239
- [ ] https://github.com/AztecProtocol/dev-rel/issues/187
```

### Timelines or important dates for initiatives:

- 

#### Educational Resources

- 3 new tutorials in the docs

#### Strategic Benefits

- Showcases what something in each of the top verticals might look like
- Help developers learn about Aztec and building in each of the verticals

### Metrics that might indicate success: 

- Number of tutorial views (requires docs tracking)
- ~~Number of tutorial completions~~ (not sure how to measure)

### Others you will lean on for this strategy:

- Rahul
- Cat
- Ze Pedro
- James

**Comment by critesjosh** [comment]
rahul mentioned that the crowdfunding application from the eng offsite could be used as the finance application, so I think we can close #228 #231 #234 and replace #237 with #187
