### ISSUE TITLE
Protocol Webinars

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#224]
### Rationale for pursuing this strategy: 

We want to do this because the Aztec protocol is complex and not easy to learn about. Creating short (~10 minute) videos will make it easier for people to learn about how Aztec works.

```[tasklist]
### Tasks
- [x] Pick 3 stable protocol topics
- [ ] Create a deck for each topic
- [ ] Present the topic at office hours, collect feedback
- [ ] https://github.com/AztecProtocol/dev-rel/issues/173
- [ ] https://github.com/AztecProtocol/dev-rel/issues/175
- [ ] https://github.com/AztecProtocol/dev-rel/issues/176
- [ ] https://github.com/AztecProtocol/dev-rel/issues/278
```

### Timelines or important dates for initiatives:

- 

#### Educational Resources

- 3 youtube videos

#### Strategic Benefits

- Simplify developer onboarding
- Assets to share with partners, in discord, in the docs
- Marketing collateral

### Metrics that might indicate success: 

- Number of recording views

### Others you will lean on for this strategy:

- Rahul
- Cat
- James
- Julian
