### ISSUE TITLE
Weekly office hours

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#225]
### Rationale for pursuing this strategy: 

We want to do this because it provides a great opportunity to engage active developers in our community. It helps the dev rel team build rapport with them as well as provide opportunities for participants to learn more about Aztec and get unstuck if they are encountering bugs. Its also an additional channel for developer to provide feedback and we can get input on parts of the developer on-boarding journey that could be improved (docs, guides, starter kits, etc.)

```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/241
- [ ] https://github.com/AztecProtocol/dev-rel/issues/240
- [ ] https://github.com/AztecProtocol/dev-rel/issues/252
- [ ] https://github.com/AztecProtocol/dev-rel/issues/258
- [ ] https://github.com/AztecProtocol/dev-rel/issues/277
- [ ] https://github.com/AztecProtocol/dev-rel/issues/259
- [x] May 30:  Aztec Accounts (James)
- [x] June 6: Fees
- [ ] https://github.com/AztecProtocol/dev-rel/issues/298
- [ ] https://github.com/AztecProtocol/dev-rel/issues/299
- [ ] https://github.com/AztecProtocol/dev-rel/issues/305
- [ ] https://github.com/AztecProtocol/dev-rel/issues/311
- [ ] https://github.com/AztecProtocol/dev-rel/issues/331
- [ ] https://github.com/AztecProtocol/dev-rel/issues/357
- [ ] https://github.com/AztecProtocol/dev-rel/issues/373
```

### Timelines or important dates for initiatives:

- 

#### Strategic Benefits

- Community building
- Developer education
- Additional information for the developer CRM (https://github.com/AztecProtocol/dev-rel/issues/213)
- Feedback on App vertical (https://github.com/AztecProtocol/dev-rel/issues/218) and Protocol Webinar (https://github.com/AztecProtocol/dev-rel/issues/224) content before recording

### Metrics that might indicate success: 

- More than 6 developers attending office hours per week

### Others you will lean on for this strategy:

- @signorecello 
- @catmcgee 
- @jzaki 
- @merfymerf

**Comment by critesjosh** [comment]
office hours notes doc https://docs.google.com/document/d/1vQf-UIMaxPzozSIvcqCxJGtAoAJDEenO3OlM_OYbHag/edit#heading=h.cbfpieggcbch
