### ISSUE TITLE
Write action descriptions for Q2 targets

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#250]
```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/213
- [ ] https://github.com/AztecProtocol/dev-rel/issues/215
- [ ] https://github.com/AztecProtocol/dev-rel/issues/219
```
