### ISSUE TITLE
[Grow App ecosystem] ELEVATE DOCS & make them self-serving

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#313]
This issue houses **general** docs improvements for Q3. 

For content updates, go here -> https://github.com/AztecProtocol/dev-rel/issues/220

### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/317
- [ ] https://github.com/AztecProtocol/dev-rel/issues/329
- [ ] https://github.com/AztecProtocol/dev-rel/issues/162
- [ ] https://github.com/AztecProtocol/dev-rel/issues/334
- [ ] https://github.com/AztecProtocol/dev-rel/issues/289
- [ ] https://github.com/AztecProtocol/dev-rel/issues/338
- [ ] https://github.com/AztecProtocol/dev-rel/issues/339
- [ ] https://github.com/AztecProtocol/dev-rel/issues/340
- [ ] https://github.com/AztecProtocol/dev-rel/issues/341
- [ ] https://github.com/AztecProtocol/dev-rel/issues/342
- [ ] https://github.com/AztecProtocol/dev-rel/issues/343
- [ ] https://github.com/AztecProtocol/dev-rel/issues/327
- [ ] https://github.com/AztecProtocol/dev-rel/issues/344
- [ ] https://github.com/AztecProtocol/dev-rel/issues/345
- [ ] https://github.com/AztecProtocol/dev-rel/issues/346
- [ ] https://github.com/AztecProtocol/dev-rel/issues/139
- [ ] https://github.com/AztecProtocol/dev-rel/issues/347
- [ ] https://github.com/AztecProtocol/dev-rel/issues/348
- [ ] https://github.com/AztecProtocol/dev-rel/issues/349
- [ ] https://github.com/AztecProtocol/dev-rel/issues/350
- [ ] https://github.com/AztecProtocol/dev-rel/issues/328
- [ ] https://github.com/AztecProtocol/dev-rel/issues/351
- [ ] https://github.com/AztecProtocol/dev-rel/issues/352
- [ ] https://github.com/AztecProtocol/dev-rel/issues/360
- [ ] https://github.com/AztecProtocol/dev-rel/issues/372
- [ ] https://github.com/AztecProtocol/dev-rel/issues/379
- [ ] https://github.com/AztecProtocol/dev-rel/issues/399
- [ ] https://github.com/AztecProtocol/dev-rel/issues/429
