### ISSUE TITLE
Noir dev support

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#324]
Dev rel is supporting various teams that are building with Noir

```[tasklist]
### Partners
- [ ] https://github.com/AztecProtocol/dev-rel/issues/332
- [ ] Eryx (Plonky 2 backend)
- [ ] Hyle
- [ ] Distributed Lab (PLUME)
- [ ] ChainSafe (PLUME)
```

```[tasklist]
### Hackathons
- [x] Level Up Hackathon (Aug 2-4th, judging)
```

```[tasklist]
### Docs
- [ ] placehodler
```
```[tasklist]
### Tasks
- [ ] zkEmail - https://github.com/orgs/noir-lang/discussions/new?category=-ncr-1-zkemail
```
