### ISSUE TITLE
Prep zkEmail libraries for NCR#1

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#356]
```[tasklist]
### Tasks
- [x] Help with judging, 25 Aug - 5 Sep ([here](https://github.com/orgs/noir-lang/discussions/categories/-ncr-1-zkemail))
- [ ] https://github.com/AztecProtocol/dev-rel/issues/365
- [x] Documentation, tutorials, etc. By Sept 5 (how-to + examples included in above point)
```

**Comment by jzaki** [comment]
Progressed via #365
New examples to own repo https://github.com/noir-lang/noir-examples/issues/21
