### ISSUE TITLE
[Grow App Ecosystem] Alpha builds

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#364]
```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/369
- [ ] https://github.com/AztecProtocol/dev-rel/issues/367
- [ ] https://github.com/AztecProtocol/dev-rel/issues/370
- [ ] https://github.com/AztecProtocol/dev-rel/issues/368
- [x] [ab1] review projects, select winners
- [x] [ab1] coordinate with marketing to announce winners
- [x] [ab1] calls with ab1 participants (demos + feedback)
- [x] [ab1] payout winners
- [ ] https://github.com/AztecProtocol/dev-rel/issues/397
- [ ] [ab3::plan] Gaming
- [x] Discord support (`#alpha-build-1`)
```
