### ISSUE TITLE
Audit Noir libraries before NCR#1

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#365]
Audit the following libraries for usability.
- Make sure they are working with the latest version of noir and bb
- Make sure READMEs have thorough info about what the library is and how to use it

```[tasklist]
### Tasks
- [x] [Noir Bignum](https://github.com/noir-lang/noir-bignum)
- [x] [Noir RSA](https://github.com/noir-lang/noir_rsa)
- [x] [Noir Base64](https://github.com/noir-lang/noir_base64)
- [ ] [String search](https://github.com/noir-lang/noir_string_search)
```

**Comment by jzaki** [comment]
BigNum updated readme and examples [here](https://github.com/noir-lang/noir-bignum/tree/jz/update-readme-egs-hc)
Base64 updated readme and examples [here](https://github.com/noir-lang/noir_base64/tree/jz/add-examples-hc)
Noir RSA had its readme and examples land in the main branch already.

Note: these will all be moved to noir-examples [here](https://github.com/noir-lang/noir-examples/issues/21)
