### ISSUE TITLE
Document Noir for 0.10.5

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#42]
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/docs/issues/352
- [ ] https://github.com/noir-lang/docs/issues/302
- [ ] https://github.com/noir-lang/docs/issues/284
```
