### ISSUE TITLE
Ensure the Aztec docs are self serve by using analytics to improve funnels and conversion for 3 key user types

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#425]
```[tasklist]
### Tasks
- [ ] Identify top 3 funnels define their conversion metrics, and then improve conversions by 33%
- [ ] Identify 3 pages to improve based on page visit and GPT questions and improve the quality of the page
- [ ] Fix 75% of outstanding structuring / issues presented by grantees e.g Nial 
```
