### ISSUE TITLE
Epic: Noir `1.0.0-beta.0` stable release to-dos

### ISSUE THREAD

**Issue by Savio-Sou** [AztecProtocol/dev-rel#461]
Pre-requisites to stable releasing Noir v1.0.0-beta.0 to a bigger audience.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/6760
- [ ] https://github.com/noir-lang/noir/issues/6762
- [ ] https://github.com/noir-lang/noir/issues/6761
- [ ] https://github.com/AztecProtocol/noir-starter/issues/97
```

Target completion date: By 17 Dec 2024

If there are more how-tos / tutorials / examples that are popular amongst the community and should be updated before Noir's stable release, do not hesitate to add them to this list.
