### ISSUE TITLE
Epic: Noir `1.0.0-beta.1` stable release to-dos

### ISSUE THREAD

**Issue by Savio-Sou** [AztecProtocol/dev-rel#465]
Pre-requisites to stable releasing Noir v1.0.0-beta.0 to a bigger audience.

```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/dev-rel/issues/464
- [ ] https://github.com/noir-lang/ec/issues/10
- [ ] https://github.com/noir-lang/schnorr/issues/5
- [ ] https://github.com/noir-lang/noir/issues/6916
```

Target completion date: By 9 Jan 2024

If there are more how-tos / tutorials / examples that are popular amongst the community and should be updated before Noir's stable release, do not hesitate to comment below / add them to this list.
